In [7]:
import pandas as pd

df = pd.read_csv("lamborghini_sales_2020_2025.csv")

df.head()

,Model,Year,Region,Color,Fuel Type,Base Price (USD),Horsepower,Sales Volume,Turbo (Yes/No)
0,Urus,2020,EMEA,Black,Gasoline,230000,641,4500,Yes
1,Urus,2020,Americas,White,Gasoline,240000,641,4800,Yes
2,Urus,2020,APAC,Red,Gasoline,235000,641,2700,Yes
3,Huracán,2020,EMEA,Yellow,Gasoline,260000,631,2500,Yes
4,Huracán,2020,Americas,Orange,Gasoline,270000,631,2600,Yes

In [8]:
df_original = df.copy()

df_original.shape

(54, 9)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

df.shape

(54, 9)

In [11]:
df.isnull().sum()

Model               0
Year                0
Region              0
Color               0
Fuel Type           0
Base Price (USD)    0
Horsepower          0
Sales Volume        0
Turbo (Yes/No)      0
dtype: int64

In [12]:
df = df.dropna()

df.shape

(54, 9)

In [13]:
df.dtypes

Model                 str
Year                int64
Region                str
Color                 str
Fuel Type             str
Base Price (USD)    int64
Horsepower          int64
Sales Volume        int64
Turbo (Yes/No)        str
dtype: object

In [14]:
text_columns = ["Model", "Region", "Color", "Fuel Type", "Turbo (Yes/No)"]

for col in text_columns:
    df[col] = df[col].str.strip().str.lower()

df.head()

,Model,Year,Region,Color,Fuel Type,Base Price (USD),Horsepower,Sales Volume,Turbo (Yes/No)
0,urus,2020,emea,black,gasoline,230000,641,4500,yes
1,urus,2020,americas,white,gasoline,240000,641,4800,yes
2,urus,2020,apac,red,gasoline,235000,641,2700,yes
3,huracán,2020,emea,yellow,gasoline,260000,631,2500,yes
4,huracán,2020,americas,orange,gasoline,270000,631,2600,yes

In [15]:
df["Turbo (Yes/No)"] = df["Turbo (Yes/No)"].map({"yes": 1, "no": 0})

df["Turbo (Yes/No)"].head()

0    1
1    1
2    1
3    1
4    1
Name: Turbo (Yes/No), dtype: int64

In [16]:
df.shape

df.head()

,Model,Year,Region,Color,Fuel Type,Base Price (USD),Horsepower,Sales Volume,Turbo (Yes/No)
0,urus,2020,emea,black,gasoline,230000,641,4500,1
1,urus,2020,americas,white,gasoline,240000,641,4800,1
2,urus,2020,apac,red,gasoline,235000,641,2700,1
3,huracán,2020,emea,yellow,gasoline,260000,631,2500,1
4,huracán,2020,americas,orange,gasoline,270000,631,2600,1

In [17]:
df.to_csv("lamborghini_sales_2020_2025_limpio.csv", index=False)

In [18]:
pivot = pd.pivot_table(df, values="Sales Volume", index="Model", aggfunc="mean")

pivot

                     Sales Volume
Model
aventador              497.500000
huracán               2765.400000
huracán (temerario)   1283.333333
revuelto              1492.666667
urus                  4525.416667
urus se               4468.666667